name: lint helm chart

on:
  pull_request:
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yaml'
  push:
    paths:
      - 'helm/**'
      - '.github/workflows/helm.yaml'
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.7.1
      -
        name: Test Helm chart
        run: helm lint helm/ip-whitelister
      -
        name: Template Helm chart
        run: helm template helm/ip-whitelister
